---
- hosts: all
  vars_prompt:

    - name: metatrader_user
      prompt: "Enter the MetaTrader user"
      private: false
      default: "metatrader"

  vars:
    github_repo: "{{ lookup('file', '/opt/metatrader-setup/.ghrepo') }}"
    github_token: "{{ lookup('env', '/opt/metatrader-setup/.ghtoken') }}"
  tasks:
    
    - name: Include tasks
      ansible.builtin.include_tasks:
        file: gh_setup.yml
  become: true
  become_user: root
