- hosts: localhost
  tasks:
    - name: Include vars for distribution
      include_vars:
        files:
          - vars/{{ ansible_distribution }}.yml
          - vars/global.yml
        paths:
          - vars
    
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ required_packages }}"