---
- hosts: all
  vars_prompt:

    - name: metatrader_user
      prompt: "Enter the MetaTrader user"
      private: false
      default: "metatrader"
  
  pre_tasks:
    - name: Install github3.py
      ansible.builtin.pip:
        name: github3.py
        state: present
    - name: Get latest release on github of rustdesk
      community.general.github_release:
        user: rustdesk
        repo: rustdesk
        action: latest_release
      register: rustdesk_release
    - name: Set package name
      ansible.builtin.set_fact:
        # example : rustdesk-1.3.8-0.aarch64.rpm
        # example : rustdesk-1.3.8-0.x86_64.deb
        # except suse : rustdesk-1.3.8-0.aarch64-suse.rpm
        rustdesk_package: "rustdesk-{{ rustdesk_release.tag_name }}-0.{{ ansible_architecture }}.{{ ansible_distribution | lower }}.{{ 'rpm' if ansible_os_family == 'RedHat' else 'deb' }}"
  tasks:
    - name: Download rustdesk
      community.general.get_url:
        url: "https://github.com/rustdesk/rustdesk/releases/download/{{ rustdesk_release.tag_name }}/{{ rustdesk_package }}"
        dest: "/tmp/{{ rustdesk_package }}"
    - name: Install rustdesk
      ansible.builtin.package:
        name: "/tmp/{{ rustdesk_package }}"
        state: present
    - name: Enable headless mode
      ansible.builtin.command:
        cmd: "rustdesk --option allow-linux-headless Y"
  become: true
  become_user: root