---
- hosts: all
  vars_prompt:
    - name: 
  pre_tasks:
    - name: Check that /opt/metatrader-setup/rustdesk_config.txt
      ansible.builtin.stat:
        path: /opt/metatrader-setup/rustdesk_config.txt
      register: config_file
      delegate_to: localhost
    - name: Get the content of /opt/metatrader-setup/rustdesk_config.txt
      ansible.builtin.slurp:
        src: /opt/metatrader-setup/rustdesk_config.txt
      delegate_to: localhost
      register: config_string
    - name: Install github3.py
      ansible.builtin.pip:
        name: github3.py
        state: present
      when: ansible_distribution != "Debian"
    - name: Install github3.py
      ansible.builtin.command:
        cmd: "pip install --break-system-packages github3.py"
      when: ansible_distribution == "Debian"
    - name: Get latest release on github of rustdesk
      community.general.github_release:
        user: rustdesk
        repo: rustdesk
        action: latest_release
      register: rustdesk_release
    - name: Set package name
      ansible.builtin.set_fact:
        # example : rustdesk-1.3.8-0.aarch64.rpm
        # example : rustdesk-1.3.8-0.x86_64.deb
        # except suse : rustdesk-1.3.8-0.aarch64-suse.rpm
        rustdesk_package: "rustdesk-{{ rustdesk_release.tag }}{{ '-0.' if ansible_os_family == 'RedHat' else '-' }}{{ ansible_architecture }}{{ '-suse' if ansible_os_family == 'Suse' }}.{{ 'rpm' if ansible_os_family == 'RedHat' else 'deb' }}"
  tasks:
    - name: Download rustdesk
      ansible.builtin.get_url:
        url: "https://github.com/rustdesk/rustdesk/releases/download/{{ rustdesk_release.tag }}/{{ rustdesk_package }}"
        dest: "/tmp/{{ rustdesk_package }}"
    - name: Install rustdesk package (RedHat/SUSE)
      ansible.builtin.yum:
        name: "/tmp/{{ rustdesk_package }}"
        state: present
      when: ansible_os_family in ['RedHat', 'Suse']
    - name: Install rustdesk package (Debian)
      ansible.builtin.apt:
        deb: "/tmp/{{ rustdesk_package }}"
        state: present
      when: ansible_os_family == 'Debian'
    - name: Enable headless mode
      ansible.builtin.command:
        cmd: "rustdesk --option allow-linux-headless Y"
    
    - name: Get the content of /opt/metatrader-setup/rustdesk_config.txt
      ansible.builtin.command:
        cmd: "rustdesk --config {{ config_string.content }}"
  become: true
  become_user: root