---
- hosts: all
  vars_prompt:

    - name: metatrader_user
      prompt: "Enter the MetaTrader user"
      private: false
      default: "metatrader"
    
    - name: metatrader_nb_profiles
      prompt: "Enter the number of MetaTrader instances"
      private: false
      default: 1
  pre_tasks:
    - name: Set public ipv4
      ansible.builtin.set_fact:
        rustdesk__relay_server_domain: "{{  ansible_default_ipv4.address }}"
    - name: install unzip
      ansible.builtin.package:
        name: unzip
        state: present
  roles:
    - roles-ansible.rustdesk
  
  post_tasks:
    - name: Create JSON data
      set_fact:
        json_data: "{{ {
          'host': rustdesk__relay_server_domain + ':'  + rustdesk__signal_server_port
          'key': _rustdesk_pubkey.content | b64decode,
          'api': '',
          'relay': rustdesk__relay_server_domain + ':' + rustdesk__relay_server_port } | to_json }}"
          
    - name: Encode JSON data to Base64
      set_fact:
        base64_encoded: "{{ json_data | b64encode | regex_replace('\\+', '-') | regex_replace('/', '_') | regex_replace('=+$', '') }}"

    - name: Reverse the encoded string
      set_fact:
        reversed_string: "{{ base64_encoded[::-1] }}"

    - name: Display the result
      debug:
        msg: "Generated config string: {{ reversed_string }}"
  become: true
  become_user: root