---
- hosts: all
  vars_prompt:
    - name: metatrader_nb_profiles
      prompt: "Enter the number of MetaTrader profiles"
      private: false
      default: 1
    
    - name: metatrader_user
      prompt: "Enter the MetaTrader user"
      private: false
      default: "metatrader"
  
  tasks:
    - name: Include tasks
      ansible.builtin.include_tasks:
        file: /opt/metatrader-setup/tasks/install_rustdesk.yml
    