---
- hosts: all
  vars_prompt:
    - name: metatrader_nb_profiles
      prompt: "Enter the number of MetaTrader profiles"
      private: false
      default: 1

    - name: metatrader_user
      prompt: "Enter the MetaTrader user"
      private: false
      default: "metatrader"

    - name: metatrader_password
      prompt: "Enter the MetaTrader password"
      private: true
      default: "metatrader"
  vars:
    github_repo: "{{ lookup('file', '$HOME/.ghrepo') }}"
    github_token: "{{ lookup('env', '$HOME/.ghtoken') }}"
    metatrader_group: "{{ metatrader_user }}"
  tasks:
    - name: Show variables
      debug:
        msg: "{{ metatrader_nb_profiles }} {{ metatrader_user }} {{ metatrader_password }} {{ metatrader_group }}"
    - name: Include role
      ansible.builtin.include_role:
        name: lpi-code.metatrader
      vars:
        metatrader_nb_profiles: "{{ metatrader_nb_profiles }}" 
        meta_trader_user: "{{ metatrader_user }}"
        metatrader_password: "{{ metatrader_password }}"
        metatrader_group: "{{ metatrader_group }}"

    
    - name: Clone repository
      ansible.builtin.git:
        repo: "{{ github_repo | regex_replace('https://', 'https://{{ github_token }}@') }}"
        dest: /home/{{ meta_trader_user }}/Desktop/SyncedGit
        update: yes
        force: yes
        clone: yes

    - name: Set permissions
      file:
        dest: /home/{{ meta_trader_user }}/Desktop/SyncedGit
        owner: "{{ meta_trader_user }}"
        group: "{{ metatrader_group }}"
        mode: '0755'

    - name: Pull in crontab
      cron:
        name: "Pull in crontab"
        minute: "*/5"
        job: "cd /home/{{ meta_trader_user }}/Desktop/SyncedGit && git pull"
        user: "{{ meta_trader_user }}"
        state: present
  become: true
  become_user: root
