---
- hosts: all
  vars_prompt:
    - name: metatrader_nb_profiles
      prompt: "Enter the number of MetaTrader profiles"
      private: false
      default: 1

    - name: metatrader_user
      prompt: "Enter the MetaTrader user"
      private: false
      default: "metatrader"

    - name: metatrader_password
      prompt: "Enter the MetaTrader password"
      private:  true # This will hide the password
      default: "metatrader"

  vars:
    github_repo: "{{ lookup('file', '/opt/metatrader-setup/.ghrepo') }}"
    github_token: "{{ lookup('env', '/opt/metatrader-setup/.ghtoken') }}"
  tasks:

    - name: Include role
      ansible.builtin.include_role:
        name: lpi-code.metatrader
    
    - name: Include tasks
      ansible.builtin.import_tasks:
        file: /opt/metatrader-setup/tasks/gh_setup.yml
  become: true
  become_user: root
