---
- hosts: all
  vars_prompt:
    - name: "metatrader_nb_profiles"
      prompt: "Enter the number of MetaTrader profiles"
      private: false
      default: 1

    - name: "metatrader_user"
      prompt: "Enter the MetaTrader user"
      private: false
      default: "metatrader"

    - name: "metatrader_password"
      prompt: "Enter the MetaTrader password"
      private: true
      default: "metatrader"

    - name: "metatrader_group"
      prompt: "Enter the MetaTrader group"
      private: false
      default: "metatrader"

  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: lpi-code.metatrader
  
    - name: Include playbook
      import_playbook: gh_setup.yml
  become: true
  become_user: root
