---
- hosts: all
  vars_prompt:
    - name: metatrader_nb_profiles
      prompt: "Enter the number of MetaTrader profiles"
      private: false
      default: 1

    - name: metatrader_user
      prompt: "Enter the MetaTrader user"
      private: false
      default: "metatrader"

    - name: metatrader_password
      prompt: "Enter the MetaTrader password"
      private:  true # This will hide the password
      default: "metatrader"
  vars:
    github_repo: "{{ lookup('file', '/opt/metatrader-setup/.ghrepo') }}"
    github_token: "{{ lookup('env', '/opt/metatrader-setup/.ghtoken') }}"
  tasks:

    - name: Include role
      ansible.builtin.include_role:
        name: lpi-code.metatrader

    
    - name: Clone repository
      ansible.builtin.git:
        repo: "{{ github_repo | regex_replace('https://', 'https://{{ github_token }}@') }}"
        dest: /home/{{ metatrader_user }}/Desktop/SyncedGit
        update: yes
        force: yes
        clone: yes

    - name: Set permissions
      file:
        dest: /home/{{ metatrader_user }}/Desktop/SyncedGit
        owner: "{{ metatrader_user }}"
        group: "{{ metatrader_group }}"
        mode: '0755'

    - name: Pull in crontab
      cron:
        name: "Pull in crontab"
        minute: "*/5"
        job: "cd /home/{{ metatrader_user }}/Desktop/SyncedGit && git pull"
        user: "{{ metatrader_user }}"
        state: present
  become: true
  become_user: root
