---
- hosts: all
  vars_prompt:
    - name: metatrader_nb_profiles
      prompt: "Enter the number of MetaTrader profiles"
      private: false
      default: 1

    - name: metatrader_user
      prompt: "Enter the MetaTrader user"
      private: false
      default: "metatrader"

    - name: metatrader_password
      prompt: "Enter the MetaTrader password"
      private:  true # This will hide the password
      default: "metatrader"
    
    - name: metatrader_restricted
      prompt: "Is the user restricted (non-admin) ?"
      private: false
      default: false

  vars:
    github_repo: "{{ lookup('file', '/opt/metatrader-setup/.ghrepo') }}"
    github_token: "{{ lookup('env', '/opt/metatrader-setup/.ghtoken') }}"
  pre_tasks:
    - name: Convert restricted to boolean
      set_fact:
        metatrader_restricted: "{{ metatrader_restricted | bool }}"

  tasks:
    - name: import role
      ansible.builtin.import_role:
        name: lpi-code.metatrader
    - name: Include tasks
      ansible.builtin.include_tasks:
        file: /opt/metatrader-setup/tasks/gh_setup.yml
      with_sequence: start=1 end={{ metatrader_nb_profiles }}
      loop_control:
        loop_var: metatrader_profile
      when: metatrader_restricted == false
    - name: Include tasks
      ansible.builtin.include_tasks:
        file: /opt/metatrader-setup/tasks/vnc_setup.yml
      vars:
        vnc_password: "{{ metatrader_password }}"
  become: true
  become_user: root