---
- hosts: all
  vars_prompt:

    - name: timezone
      prompt: "Enter the timezone"
      private: false
      default: "Europe/Berlin"
    
    - name: unblock_minutes
      prompt: "Enter the minutes at which the access will be unblocked (0-59)"
      private: false
      default: 0
    
    - name: unblock_hours
      prompt: "Enter the hours at which the access will be unblocked"
      private: false
      default: 0
    
    - name: unblock_days
      prompt: "Enter the days at which the access will be unblocked"
      private: false
      default: 0

    - name: unblock_weeks
      prompt: "Enter the weeks at which the access will be unblocked"
      private: false
      default: 0
    
    - name: unblock_months
      prompt: "Enter the months at which the access will be unblocked"
      private: false
      default: 0

  
  tasks:
    - name: Checking time format
      assert:
        that:
          - unblock_minutes | type_debug == "int"
          - unblock_hours | type_debug == "int"
          - unblock_days | type_debug == "int"
          - unblock_weeks | type_debug == "int"
          - unblock_months | type_debug == "int"
        fail_msg: "Time format is not correct"
      
    - name: Include tasks
      ansible.builtin.import_tasks:
        file: /opt/metatrader-setup/tasks/time_restriction.yml
  become: true
  become_user: root
