---
- hosts: all
  vars_prompt:

    - name: close_access_time
      prompt: "Enter the time to close access format HH:MM"
      private: false
      default: "22:00"

    - name: open_access_time
      prompt: "Enter the time to (re)open access format HH:MM"
      private: false
      default: "06:00"
    
    - name: timezone
      prompt: "Enter the timezone"
      private: false
      default: "Europe/Berlin"
  
  tasks:
  
    - name: Include tasks
      ansible.builtin.import_tasks:
        file: /opt/metatrader-setup/tasks/time_restriction.yml
  become: true
  become_user: root
