---
- hosts: all
  vars_prompt:

    - name: timezone
      prompt: "Enter the timezone"
      private: false
      default: "Europe/Berlin"
    
    - name: unblock_time
      prompt: "Enter the date in iso format at which the equipment will be unblocked"
      private: false
      default: 0
  
  tasks:
    - name: Include tasks
      ansible.builtin.import_tasks:
        file: /opt/metatrader-setup/tasks/time_restriction.yml
  become: true
  become_user: root
