- name: Create directory
  file:
    dest: /home/{{ metatrader_user }}/Desktop/MQL5/Experts
    owner: "{{ metatrader_user }}"
    group: "{{ metatrader_user }}"
    mode: '0755'
    state: directory
    recurse: yes

- name: Install git
  ansible.builtin.package:
    name: git
    state: present

- name: Clone repository
  ansible.builtin.command:
    cmd: "git clone {{ github_repo }} /home/{{ metatrader_user }}/Desktop/MQL5/Experts/RM"
    creates: /home/{{ metatrader_user }}/Desktop/MQL5/Experts/RM
  become: true
  become_user: "{{ metatrader_user }}"

  
- name: Force permission on all files
  file:
    dest: /home/{{ metatrader_user }}/Desktop/MQL5/Experts/RM
    owner: "{{ metatrader_user }}"
    group: "{{ metatrader_user }}"
    mode: '0755'
    recurse: yes
    state: directory

- name: Pull in crontab
  cron:
    name: "Pull in crontab"
    minute: "*/5"
    job: "cd /home/{{ metatrader_user }}/Desktop/MQL5/Experts/RM && git pull"
    user: "{{ metatrader_user }}"
    state: present