- name: Set distant path
  set_fact:
    distant_path: "/home/{{ metatrader_user }}/.mt5_{{ metatrader_profile }}/drive_c/Program Files/MetaTrader 5/MQL5/Experts"

- name: Create directory
  file:
    dest: "{{ distant_path }}"
    owner: "{{ metatrader_user }}"
    group: "{{ metatrader_user }}"
    mode: '0755'
    state: directory
    recurse: yes

- name: Install git
  ansible.builtin.package:
    name: git
    state: present

- name: Clone repository
  ansible.builtin.command:
    cmd: "git clone {{ github_repo }} '{{ distant_path }}/RM'"
    creates: "{{ distant_path }}/RM"
  become: true
  become_user: "{{ metatrader_user }}"

- name: Force permission on all files
  file:
    dest: "{{ distant_path }}"
    owner: "{{ metatrader_user }}"
    group: "{{ metatrader_user }}"
    mode: '0755'
    recurse: yes
    state: directory

- name: Pull in crontab
  cron:
    name: "Pull in crontab"
    minute: "*/5"
    job: "cd /home/{{ metatrader_user }}/Desktop/MQL5/Experts/RM && git pull"
    user: "{{ metatrader_user }}"
    state: present