- name: Set timezone
  ansible.builtin.timezone:
    name: "{{ timezone }}"

- name: Locally set timezone
  set_fact:
    ansible_local:
      timezone: "{{ timezone }}"
  
- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted

- name: Remove ufw
  ansible.builtin.package:
    name: ufw
    state: absent

- name: Install iptables
  ansible.builtin.package:
    name:
      - iptables
      - conntrack
    state: present
- name: Get user number (UID)
  getent:
    database: passwd
    key: "{{ metatrader_user }}"
  register: user_info
  changed_when: false

- name: Set user UID fact
  set_fact:
    user_uid: "{{ user_info.ansible_facts.getent_passwd[metatrader_user][1] }}"
  changed_when: false

- name: Calculate VNC port
  set_fact:
    vnc_port: "{{ 5900 + user_uid | int - 1000 }}"

- name: Set automatic open access
  cron:
    name: "automatic open access"
    minute: "{{ (unblock_date | to_datetime).minute }}"
    hour: "{{ (unblock_date | to_datetime).hour }}"
    day: "{{ (unblock_date | to_datetime).day }}"
    month: "{{ (unblock_date | to_datetime).month }}"
    job: >
      iptables -F &&
      crontab -l | grep -v "automatic open access" | crontab -
    user: root
    state: present

- name: Get date 
  command: date "+%Y-%m-%d %H:%M:%S"
  environment:
    TZ: "{{ timezone }}"
  register: current_date
  changed_when: false

- name: Close in 1 minute from now
  cron:
    name: "automatic close access {{ item }}"
    minute: "{{ (current_date.stdout | to_datetime).minute + 1 }}"
    hour: "{{ (current_date.stdout | to_datetime).hour }}"
    day: "{{ (current_date.stdout | to_datetime).day }}"
    month: "{{ (current_date.stdout | to_datetime).month }}"
    job: >
      conntrack -D -p tcp --dport {{ item }} &&
      iptables -D INPUT -p tcp --dport {{ item }} -j ACCEPT 2>/dev/null || true &&
      iptables -A INPUT -p tcp --dport {{ item }} -j DROP &&
      crontab -l | grep -v "{{ item }}" | crontab -
    user: root
    state: present
  with_items:
    - 22  # SSH
    - "{{ vnc_port }}"  # VNC