- name: Check time is in the right format
  assert:
    that:
      - open_access_time.split(':')[0] | int >= 0 and open_access_time.split(':')[0] | int <= 23
      - open_access_time.split(':')[1] | int >= 0 and open_access_time.split(':')[1] | int <= 59
      - close_access_time.split(':')[0] | int >= 0 and close_access_time.split(':')[0] | int <= 23
      - close_access_time.split(':')[1] | int >= 0 and close_access_time.split(':')[1] | int <= 59
    fail_msg: "Time format is not correct"

- name: Set timezone
  ansible.builtin.timezone:
    name: "{{ timezone }}"

- name: Remove ufw
  ansible.builtin.package:
    name: ufw
    state: absent

- name: Install nftables
  ansible.builtin.package:
    name: nftables
    state: present

- name: Ensure nftables inet filter table and input chain exist
  ansible.builtin.command:
    cmd: "nft create table inet filter"
  ignore_errors: yes

- name: Ensure nftables input chain exists
  ansible.builtin.command:
    cmd: 'nft create chain inet filter input { type filter hook input priority 0 \; }'
  ignore_errors: yes

- name: Allow ssh and rdp
  ansible.builtin.command:
    cmd: "nft add rule inet filter input tcp dport {{ item }} accept"
  with_items:
    - 22  # SSH
    - 3389  # RDP

- name: Set automatic open access
  cron:
    name: "automatic open access {{ item }}"
    minute: "{{ open_access_time.split(':')[1] }}"
    hour: "{{ open_access_time.split(':')[0] }}"
    job: "nft add rule inet filter input tcp dport {{ item }} accept"
    user: root
    state: present
  with_items:
    - 22  # SSH
    - 3389  # RDP

- name: Set automatic close access
  cron:
    name: "automatic close access {{ item }}"
    minute: "{{ close_access_time.split(':')[1] }}"
    hour: "{{ close_access_time.split(':')[0] }}"
    job: conntrack -D -p tcp --dport {{ item }} && nft delete rule inet filter input tcp dport {{ item }} accept
    user: root
    state: present
  with_items:
    - 22  # SSH
    - 3389  # RDP

- name: Ensure nftables is enabled
  ansible.builtin.service:
    name: nftables
    enabled: yes
    state: started
