- name: Set timezone
  ansible.builtin.timezone:
    name: "{{ timezone }}"

- name: Locally set timezone
  set_fact:
    ansible_local:
      timezone: "{{ timezone }}"
  
- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted

- name: Remove ufw
  ansible.builtin.package:
    name: ufw
    state: absent

- name: Install iptables
  ansible.builtin.package:
    name:
      - iptables
      - conntrack
    state: present

- name: Set automatic open access
  cron:
    name: "automatic open access {{ metatrader_user }}"
    minute: "{{ (unblock_date | to_datetime).minute }}"
    hour: "{{ (unblock_date | to_datetime).hour }}"
    day: "{{ (unblock_date | to_datetime).day }}"
    month: "{{ (unblock_date | to_datetime).month }}"
    job: >
      systemctl start vncserver@{{ metatrader_user_id }}.service &&
      crontab -l | grep -v "automatic open access {{ metatrader_user }}" | crontab -
    user: root
    state: present

- name: Get date 
  command: date "+%Y-%m-%d %H:%M:%S"
  environment:
    TZ: "{{ timezone }}"
  register: current_date
  changed_when: false

- name: Close in 2 minute from now (minimum to avoid error)
  cron:
    name: "automatic close access {{ metatrader_user }}"
    minute: "{{ (current_date.stdout | to_datetime).minute + 2 }}"
    hour: "{{ (current_date.stdout | to_datetime).hour }}"
    day: "{{ (current_date.stdout | to_datetime).day }}"
    month: "{{ (current_date.stdout | to_datetime).month }}"
    job: >
      /usr/bin/vncserver -kill :{{ metatrader_user_id }} &&
      systemctl stop vncserver@{{ metatrader_user_id }}.service &&
      crontab -l | grep -v "automatic close access {{ metatrader_user }}" | crontab -
    user: root
    state: present