- name: Set timezone
  ansible.builtin.timezone:
    name: "{{ timezone }}"

- name: Locally set timezone
  set_fact:
    ansible_local:
      timezone: "{{ timezone }}"
  
- name: Set unblock date
  set_fact:
    unblock_date: "{{ now() + timedelta(minutes=unblock_minutes, hours=unblock_hours, days=unblock_days, weeks=unblock_weeks, months=unblock_months) }}"

- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted

- name: Remove ufw
  ansible.builtin.package:
    name: ufw
    state: absent

- name: Install iptables
  ansible.builtin.package:
    name:
      - iptables
      - conntrack
    state: present

- name: Set automatic open access
  cron:
    name: "automatic open access"
    job: >
      iptables -F
    user: root
    state: present

- name: Close in 1 minute from now
  cron:
    name: "automatic close access {{ item }}"
    minute: "{{ unblock_date.minute }}"
    hour: "{{ unblock_date.hour }}"
    day: "{{ unblock_date.day }}"
    month: "{{ unblock_date.month }}"
    job: >
      conntrack -D -p tcp --dport {{ item }} &&
      iptables -D INPUT -p tcp --dport {{ item }} -j ACCEPT 2>/dev/null || true &&
      iptables -A INPUT -p tcp --dport {{ item }} -j DROP
    user: root
    state: present
  with_items:
    - 22  # SSH
    - 3389  # RDP
