- name: Install WireGuard and qrencode
  apt:
    name:
      - wireguard
      - qrencode
    state: present
    update_cache: yes

- name: Generate WireGuard private key
  command: wg genkey | tee /etc/wireguard/privatekey
  args:
    creates: /etc/wireguard/privatekey

- name: Generate WireGuard public key
  command: cat /etc/wireguard/privatekey | wg pubkey | tee /etc/wireguard/publickey
  args:
    creates: /etc/wireguard/publickey

- name: Create WireGuard configuration directory
  file:
    path: /etc/wireguard
    state: directory
    mode: '0700'

- name: Create WireGuard configuration file
  template:
    src: wireguard.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: '0600'

- name: Enable and start WireGuard service
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started

- name: Create client configuration directory
  file:
    path: /etc/wireguard/clients
    state: directory
    mode: '0700'

- name: Generate client keys
  command: wg genkey | tee /etc/wireguard/clients/{{ item }}_privatekey
  args:
    creates: /etc/wireguard/clients/{{ item }}_privatekey
  loop: "{{ wireguard_clients }}"

- name: Generate client public keys
  command: cat /etc/wireguard/clients/{{ item }}_privatekey | wg pubkey | tee /etc/wireguard/clients/{{ item }}_publickey
  args:
    creates: /etc/wireguard/clients/{{ item }}_publickey
  loop: "{{ wireguard_clients }}"

- name: Create client configuration files
  template:
    src: client.conf.j2
    dest: /etc/wireguard/clients/{{ item }}.conf
    mode: '0600'
  loop: "{{ wireguard_clients }}"

- name: Add client public keys to server configuration
  lineinfile:
    path: /etc/wireguard/wg0.conf
    insertafter: '^# Client'
    line: "[Peer]\nPublicKey = {{ lookup('file', '/etc/wireguard/clients/' + item + '_publickey') }}\nAllowedIPs = 0.0.0.0/0"
  loop: "{{ wireguard_clients }}"
  notify: Restart WireGuard

- name: Generate QR codes for client configurations
  command: qrencode -t png -o /etc/wireguard/clients/{{ item }}.png < /etc/wireguard/clients/{{ item }}.conf
  args:
    creates: /etc/wireguard/clients/{{ item }}.png
  loop: "{{ wireguard_clients }}"

- name: Restart WireGuard service
  systemd:
    name: wg-quick@wg0
    state: restarted
